---
# tasks file for ssh
- name: Ensure user accounts are present
  user:
    name={{ item.name }}
    shell=/bin/bash
    group=sudo
    state=present
    generate_ssh_key=yes
    ssh_key_bits=2048
    ssh_key_file=.ssh/id_rsa
  with_items: ssh_users

- name: Ensure public keys are installed
  authorized_key:
    user={{ item.name }}
    key="{{ item.key }}"
  with_items: ssh_users
  notify: restart ssh