---
# tasks file for ssh
- name: Ensure user accounts are present
  user:
    name={{ os_user }}
    shell=/bin/bash
    group=sudo
    state=present
    generate_ssh_key=yes
    ssh_key_bits=2048
    ssh_key_file=.ssh/id_rsa

- name: Ensure public keys are installed
  authorized_key:
    user={{ os_user }}
    key="{{ lookup('file', os_user_public_key) }}"
  notify: restart ssh