---
# tasks file for git
- name: "Install git"
  apt: pkg=git-core state=installed

- name: "Install global gitignore"
  copy: src=.gitignore dest="{{ git_gitignore_path }}" mode=0655

- name: "Configure git"
  template:
    src=gitconfig.j2
    dest="/home/{{ git_os_user }}/.gitconfig"