---
# tasks file for docker
- name: "Install apt keys"
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: "Update apt"
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_version_name }} main" state=present

- name: "Install docker"
  apt: pkg=docker-engine update_cache=yes

- name: "Start daemon"
  service: name=docker state=started